### ISSUE TITLE
Create NPM package instead of submodule

### ISSUE THREAD

**Issue by jvanbaarsen** [appsignal/design-system#1]
We currently use this system as a git submodule, but we also want to look at using it as an NPM package where Tailwind etc is included in the package as a dependency.

Current problem I run into:

**yarn link doesn't install subdependencies**
When I try to use `yarn link` Tailwind is not installed as a dependency.

**Using yalc as a tool to make the above work**
In this case you would need to link again every time you make a change in the package.

In order to convert this to a package it needs to take care of the following:
* Tailwind should be a dependency of this package
* When developing you should not need to stop servers etc to reload this dependency

**Comment by jvanbaarsen** [comment]
Adam, Tom and I had a call to go over changes that Adam made to make this work (Thanks adam 💛 )

Tradeoffs we discussed:

| Submodule | NPM package |
|------------|----------------|
| Easy to discover code (It is in the project) | We create a small barrier on adding custom CSS because it is in a package|
| We can easily select which components we want to include | Adding the design language is a matter of adding one dependency and one line in the bundle entry point|

After discussing we decided that the NPM package is worth the trade-offs, and we are planning on moving this way.

We have a couple of things open that we want to solve in the (near) future:
* Be able to easily discover the code in the package
* Make it so that images/fonts don't have to remain in the `dist` folder
* Figure out a proper way of versioning
* Make the package experience awesome for new developers.

**Comment by wesoudshoorn** [comment]
@jvanbaarsen I think this currently works with the NPM package, right?

**Comment by jvanbaarsen** [comment]
yes it can :)
