### ISSUE TITLE
Button-elements with button component classes spacing is off

### ISSUE THREAD

**Issue by tombruijn** [appsignal/design-system#14]
Browser: Firefox

## button-element
![image](https://user-images.githubusercontent.com/282402/69968929-bdc00600-151b-11ea-89db-f544b54b271a.png)

```html
<button class="c-button c-button--sm">Go</button>
```

## a-element
![image](https://user-images.githubusercontent.com/282402/69968999-da5c3e00-151b-11ea-9d7d-f62f2b7e56ce.png)

```html
<a class="c-button c-button--sm">Go</a>
```

**Comment by jvanbaarsen** [comment]
@tombruijn Which version of Firefox are you using? I tried reproducing this but doesn't seem to be a problem in my Firefox (I'm using:  70.0.1)

**Comment by tombruijn** [comment]
At the time I was using 70.x probably. Now 71.

Not seeing it anymore either. Maybe it was a broken build? It's still rendering inconsistently for me sometimes.
