### ISSUE TITLE
keep `c-content` or `c-markdown` around

### ISSUE THREAD

**Issue by jvanbaarsen** [appsignal/design-system#18]
I think we currently have two ways of rendering markdown. either via the `c-content` or the `c-markdown` class. The `c-markdown` is more feature complete.

Should we drop `c-content` in favour of `c-markdown`?

**Comment by wesoudshoorn** [comment]
I like `c-markdown` because it implies default styling for all markdown tags available, but we might have content pages with richer content than just markdown. We also have some extra flavors of markdown within the blog/docs?
