### ISSUE TITLE
Figure out if we need the grid.css file

### ISSUE THREAD

**Issue by jvanbaarsen** [appsignal/design-system#7]
We currently have a `grid.css` component file, this file includes a whole bunch of Grid helpers. I'm wondering if we actually need all of these, since we also use the `Tailwindcss-grid` plugin.

It feels like we need to make a choice here, either make them ourselves or go with the plugin.

@wesoudshoorn What is your idea about this?

**Comment by wesoudshoorn** [comment]
I think we can lose our whole setup, but I do think that there's probably gonna be some layout grids we can define here, so we can easily create custom layouts for the blog, docs etc. : `.grid--blog`, `.grid--app`, `.grid--docs`

**Comment by jvanbaarsen** [comment]
We removed the custom `grid` classes in #32
